### ISSUE TITLE
Brainstorm UI/UX ideas

### ISSUE THREAD

**Issue by Sarrasor** [Sarrasor/INNO-S20-SP#33]

**Comment by alkaitagi** [comment]
First, I believe we need to put the necessary terminology to work. When we talk about UI, we talk about 2 "types" of it: overlay and world-space. Overlay UI lives on your devices' screen space. However you physically move your device, such UI will not move relatively to its screen position. An example of such UI is the circular "message" button on the screen shot Daniil sent recently.

Contrary we have world-space UI, like those panels and button showed in the last HoloLens pipeline video. Such UI exists in virtual physical space and is anchored to real physical position. So when you physically move your device such UI moves relatively to its screen position.

Now, given the simplicity of our current instruction/slide form, I don't think now we need any world-space UI. Then, given the fact that phones' screen-space is very small, and coming back to the fact that our instructions/slides are simple, I also believe we should avoid having overlay buttons. Not to clutter already limited view and to have our content conveniently observable even from devices with smaller screen diagonals.

The only overlay UI I would like to have is simple [current / total] slides counter at the top of the screen. With small font-size and semitransparent color. We would need to extensively utilize gesture controls:
- swipe left/right - go to previous/next slide.
- double tap - zoom in/out to the object (technically, scale it up/down).
- going back to Instructions list - the "back" button on the native Android navigation bar.
- swipe up - bring slides list to the bottom of the screen, that is semitransparent and horizontally scrollable, as an alternative navigation option. (similar UI can be found on Android's YouTube app)

![image](https://user-images.githubusercontent.com/32439229/77844453-bc43d900-71af-11ea-8aec-ab20789e209d.png)
